language: cpp
env:
  global:
    - BOOTSTRAP_LATEX="1"
    
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - cd .. 
  - sudo apt-get install -qq subversion
  - sudo apt-get install -qq rsync
  - sudo apt-get install -qq ttf-sil-gentium ttf-sil-gentium-basic
  - sudo apt-get install -qq texinfo ttf-inconsolata
  - sudo apt-get install -qq texlive-xetex texlive-latex-recommended texlive-latex-extra
  - svn checkout https://svn.r-project.org/R/trunk/ r-devel
  - cd r-devel/
  - ./tools/rsync-recommended
  - CXX1X="g++-4.8" CXX1XSTD="-std=c++11"  ./configure --enable-R-shlib --without-x
  - make
  - sudo make install
  - cd ../Rcpp11
  - ./travis-tool.sh github_package testthat
    
script:
  - cd ..
  - R CMD build --no-manual Rcpp11
  - FILE=$(ls -1t Rcpp11_*.tar.gz | head -n 1)
  - R CMD check --no-manual --as-cran "${FILE}"
  - R CMD INSTALL "${FILE}"
  - git clone https://github.com/romainfrancois/Rcpp-test.git
  - Rscript -e "setwd('Rcpp-test'); library(methods); library(testthat); library(Rcpp11); test_dir('.')"
  
after_script:
  - ./travis-tool.sh dump_logs
  
notifications:
  email:
    on_success: change
    on_failure: change

    
