language: cpp

env:
  global:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
    
before_install:
  - export CC="gcc-4.8 -std=gnu99"
  - export CXX="g++-4.8 -std=c++11"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package testthat
  - mkdir ~/.R
  - echo -e "CC=gcc-4.8 -std=gnu99\nCXX=g++-4.8 -std=c++11\nCXXFLAGS=-g 03\nCFLAGS=-g -03\n" > ~/.R/Makevars
  - cd .. 
  - sudo apt-get install -qq subversion
  - sudo apt-get install -qq rsync
  - sudo apt-get install -qq ttf-sil-gentium ttf-sil-gentium-basic
  - sudo apt-get install -qq texinfo texlive-fonts-extra ttf-inconsolata ttf-droid
  - sudo apt-get install -qq texlive-xetex texlive-latex-recommended texlive-latex-extra
  - svn checkout https://svn.r-project.org/R/trunk/ r-devel
  - cd r-devel/
  - ./configure --enable-R-shlib --without-x --without-recommended-packages
  - make
  - sudo make install
  - cd Rcpp11
    
script: 
  - ./travis-tool.sh run_tests
  # - FILE=$(ls -1t Rcpp11_*.tar.gz | head -n 1)
  # - R CMD INSTALL "${FILE}"
  # - git clone https://github.com/romainfrancois/Rcpp-test.git
  # - Rscript -e "setwd('Rcpp-test'); library(methods); library(testthat); library(Rcpp11); test_dir('.')"
  
after_failure:
  - ./travis-tool.sh dump_logs
  
notifications:
  email:
    on_success: change
    on_failure: change

    

