language: cpp

env:
  global:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
    
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package testthat
  - mkdir ~/.R
  # - echo -e "CC=clang\nCXX=clang++\nCXXFLAGS=-std=c++11 -stdlib=libc++\n" > ~/.R/Makevars
    
script: 
  - ./travis-tool.sh run_tests
  - FILE=$(ls -1t Rcpp11_*.tar.gz | head -n 1)
  - R CMD INSTALL "${FILE}"
  - git clone https://github.com/romainfrancois/Rcpp-test.git
  - cd Rcpp-test
  - Rscript -e "library(methods); library(testthat); library(Rcpp11); test_dir('.')"
  - cd ..
  
after_failure:
  - ./travis-tool.sh dump_logs
  
notifications:
  email:
    on_success: change
    on_failure: change

    

